inshlh te5dem

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -12,10 +12,15 @@ jobs:
         uses: actions/checkout@v3
       
       - name: Login to Docker Hub
-        uses: docker/login-action@v2
-        with:
-          username: ${{ secrets.dockerhub.DOCKER_USERNAME }}
-          password: ${{ secrets.dockerhub.DOCKER_PASSWORD }}
+        run: |
+          echo "Logging in to Docker Hub..."
+          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+          if [ $? -eq 0 ]; then
+            echo "Docker login successful"
+          else
+            echo "Docker login failed"
+            exit 1
+          fi
       
       - name: Build Docker image
         run: docker build -t hadil2003/react-test -f Dockerfile.dev .
